# Site settings
title: Botleg
email: blog@botleg.com
author: Hanzel Jesheen
description: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nisi quia illo impedit consequatur nihil nam in esse architecto labore cum voluptatem officia, perspiciatis itaque non libero aperiam, placeat, eaque vel.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://botleg.com" # the base hostname & protocol for your site
github_username:  botleg
permalink: /stories/:categories/:title
exclude: [config.rb, Gemfile, Gemfile.lock, Rakefile, assets/sass]

# Build settings
markdown: kramdown

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      bg: "background-image:-webkit-radial-gradient(50% 0%, circle, #8abb5d,#42736f);background-image:radial-gradient(circle at 50% 0%, #8abb5d,#42736f);"

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-assets
  - jekyll-minifier

# Plugin: jekyll-assets
assets:
  dirname: assets
  sources:
    - assets/
  js_compressor: uglifier
  autosize: false
  cachebust: none
  gzip: false
  cache: false
  debug: false

# Plugin: jekyll-minifier
jekyll-minifier:
  exclude: ['*.xml', '*.css', '*.js']