# Site settings
title: Botleg
email: blog@botleg.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://botleg.com" # the base hostname & protocol for your site
github_username:  botleg
permalink: /stories/:categories/:title
exclude: [config.rb, Gemfile, Gemfile.lock, Rakefile, assets/js, assets/sass]

# Build settings
markdown: kramdown

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-assets
  - jekyll-press

# Plugin: jekyll-assets
jekyll-press:
  exclude: ['feed.xml', '*.js', '*.css']

# Plugin: jekyll-assets
assets:
  dirname: assets
  sources:
    - assets/js
    - assets/images
  js_compressor: uglifier
  autosize: false
  cachebust: none
  gzip: false
  cache: false
  debug: false