# Site settings
title: Botleg
email: blog@botleg.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://botleg.com" # the base hostname & protocol for your site
github_username:  botleg
permalink: /stories/:categories/:title

# Build settings
markdown: kramdown

# SASS Settings
sass:
    style: :compressed

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-assets

# Plugin: jekyll-assets
assets:
  dirname: _
  baseurl: /_/
  sources:
    - _/js
    - _/css
    - _/images
  js_compressor: uglifier
  css_compressor: sass
  autosize: false
  cachebust: none
  gzip: false
  cache: false
  debug: false