# Site settings
title: Botleg
email: blog@botleg.com
author: Hanzel Jesheen
description: Hi, botleg is a blog where you can find tutorials and techniques in web development, big data analysis, databases, cloud computing and anything related to technology.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://botleg.com" # the base hostname & protocol for your site
github_username:  botleg
permalink: /stories/:categories/:title
exclude: [config.rb, Gemfile, Gemfile.lock, Rakefile, assets/sass]

# Build settings
markdown: redcarpet
highlighter: pygments

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      bg: "background-image:-webkit-radial-gradient(50% 0%, circle, #8abb5d,#42736f);background-image:radial-gradient(circle at 50% 0%, #8abb5d,#42736f);"
      popular: false

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-assets
  - jekyll-minifier

# Plugin: jekyll-assets
assets:
  dirname: assets
  sources:
    - assets/
  js_compressor: uglifier
  autosize: false
  cachebust: none
  gzip: false
  cache: false
  debug: false

# Plugin: jekyll-minifier
jekyll-minifier:
  exclude: ['*.xml', '*.css', '*.js']