# Site settings
title: Botleg
email: blog@botleg.com
author: Hanzel Jesheen
description: Hi, botleg is a blog where you can find tutorials and techniques in web development, devops, databases, cloud computing and anything related to technology.
baseurl: ""
url: "https://botleg.com"
github_username:  botleg
permalink: /stories/:title/
paginate: 7
paginate_path: "/blog/:num"
exclude: [Gemfile, Gemfile.lock, Rakefile, assets/js, assets/sass, assets/images/blog, gulpfile.js, package.json, '*.log', node_modules]
keep_files: [assets, .git, CNAME, .nojekyll]
env: production

# Build settings
markdown: kramdown
highlighter: rouge

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      bg: "background:rgb(155, 89, 182);background-image:linear-gradient(90deg, rgb(155, 89, 182) 25%, rgb(41, 128, 185) 100%);background-image:-moz-linear-gradient(left, rgb(155, 89, 182) 25%, rgb(41, 128, 185) 100%);background-image:webkit-linear-gradient(left, rgb(155, 89, 182) 25%, rgb(41, 128, 185) 100%);background-image:-o-linear-gradient(left, rgb(155, 89, 182) 25%, rgb(41, 128, 185) 100%);background-image:-ms-linear-gradient(left, rgb(155, 89, 182) 25%, rgb(41, 128, 185) 100%);"

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-paginate